"""Generate embedded resources from the complete public JSON inputs (stdlib only)."""
import hashlib
import json
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src/NightreignRelicTool/Resources'
OUTPUT = ROOT / '_build/release-resources'
INPUTS = (
    ('ui-text.json', 'NightreignRelicTool.Localization.Ui.json'),
    ('game-text-1.03.5.json', 'NightreignRelicTool.Localization.Game.json'),
    ('game-text-bindings-1.03.5.json', 'NightreignRelicTool.Localization.Bindings.json'),
    ('relic-scoring-model-1.03.5.json', 'NightreignRelicTool.Resources.ScoringModel.gz'),
    ('custom-effect-search-1.03.5.json', 'NightreignRelicTool.Resources.CustomEffectSearch.gz'),
)


def write_changed(path, data):
    if not path.exists() or path.read_bytes() != data:
        path.write_bytes(data)


def compress(raw):
    # Fixed gzip header: no filename, zero timestamp, level 9, Windows/NTFS marker.
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)
    packed = (b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x0a'
              + compressor.compress(raw) + compressor.flush()
              + struct.pack('<II', zlib.crc32(raw), len(raw) & 0xffffffff))
    if zlib.decompress(packed, 31) != raw:
        raise ValueError('Resource compression round trip failed')
    return packed


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    records = []
    for filename, logical in INPUTS:
        # Preserve exact UTF-8 bytes, including official text and binding order.
        raw = (SOURCE / filename).read_bytes()
        value = json.loads(raw)
        packed = compress(raw)
        write_changed(OUTPUT / (filename + '.gz'), packed)
        records.append(dict(file=filename + '.gz', logicalName=logical,
                            decodedBytes=len(raw), compressedBytes=len(packed), entries=len(value),
                            decodedSha256=hashlib.sha256(raw).hexdigest().upper(),
                            compressedSha256=hashlib.sha256(packed).hexdigest().upper()))
    lines = ['// Generated by tools/prepare_release_resources.py; contains no local paths.',
             'namespace NightreignRelicTool.Localization {',
             'internal static class ReleaseResourceIntegrity {',
             'internal static string ExpectedHash(string name) { switch(name) {']
    for item in records:
        lines.append('case "' + item['logicalName'] + '": return "' + item['decodedSha256'] + '";')
    lines += ['default: throw new System.IO.InvalidDataException("Unknown embedded resource.");',
              '} }', 'internal static int ExpectedLength(string name) { switch(name) {']
    for item in records:
        lines.append('case "' + item['logicalName'] + '": return ' + str(item['decodedBytes']) + ';')
    lines += ['default: throw new System.IO.InvalidDataException("Unknown embedded resource.");', '} }', '} }']
    write_changed(OUTPUT / 'ReleaseResourceIntegrity.g.cs', ('\n'.join(lines) + '\n').encode('utf-8'))
    write_changed(OUTPUT / 'manifest.json', (json.dumps(records, indent=2) + '\n').encode('utf-8'))
    print('PASS: five public resource inputs compressed and verified.')


if __name__ == '__main__':
    main()
